name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: install ubuntu packages
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install -y libudev-dev libgtk-3-dev
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ksm2usc-score-import-${{ runner.os }}
        path: |
          target/release/ksm2usc-score-import*
          !target/release/ksm2usc-score-import.d
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ~/artifacts
    - name: Rename files
      run: |
        tar -czf ksm2usc-score-import-Linux.tar.gz ~/artifacts/ksm2usc-score-import-Linux/ksm2usc-score-import
        tar -czf ksm2usc-score-import-macOS.tar.gz ~/artifacts/ksm2usc-score-import-macOS/ksm2usc-score-import
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /home/runner/artifacts/ksm2usc-score-import-Windows/ksm2usc-score-import.exe
          ksm2usc-score-import-Linux.tar.gz
          ksm2usc-score-import-macOS.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

